//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studies2020.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentIspits = new HashSet<StudentIspit>();
        }
    
        public int idStudent { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public int indeksBroj { get; set; }
        public int indeksGodina { get; set; }
        public string indeksCalc { get; set; }
        public string imePrezime { get; set; }
        public string prezimeIme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentIspit> StudentIspits { get; set; }
    }
}
